### ISSUE TITLE
RTF build is broken

### ISSUE THREAD

**Issue by jason-p-pickering** [dhis2/DeansDashboardDocs#10]
Looks like this may not be possible to fix, at least easily. 
https://issues.apache.org/jira/browse/FOP-2182

**Comment by litlfred** [comment]
Are we perhaps doing something that was triggering the error?

Cheers,
-carl

On Feb 10, 2015 6:57 AM, Jason Pickering <notifications@github.com> wrote:

Looks like this may not be possible to fix, at least easily.
