### ISSUE TITLE
can't clone dhis2tools

### ISSUE THREAD

**Issue by litlfred** [dhis2/DeansDashboardDocs#2]
main:
     [exec] Cloning into 'src/docbkx/en/dhis2tools'...
     [exec] Permission denied (publickey).
     [exec] fatal: Could not read from remote repository.
     [exec] 
     [exec] Please make sure you have the correct access rights
     [exec] and the repository exists.
     [exec] Clone of 'git@github.com:dhis2/dhis2tools.git' into submodule path 'src/docbkx/en/dhis2tools' failed
     [exec] Result: 1

**Comment by jason-p-pickering** [comment]
Removed submodule dependency: Please try again and close if it works.

**Comment by jason-p-pickering** [comment]
Have removed the dependency. Please try again and close if fixed.

**Comment by litlfred** [comment]
fixed.  thanks
